
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param fromRevisionId The id of the revision
 * @param toRevisionId The id of the revision
 * @param changeTypes (optional, array of change types to filter, NULL for all)
 * @param includeSystem Whether to include system tables (default false)
 */
export const countTableDiffsBetweenRevisions = $runtime.makeTypedQueryFactory("\nWITH parent_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $1 AND \"t1\".\"B\" IS NOT NULL))\nAND ($4::boolean IS TRUE OR \"Table\".\"system\" = FALSE)),\nchild_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $2 AND \"t1\".\"B\" IS NOT NULL))\nAND ($4::boolean IS TRUE OR \"Table\".\"system\" = FALSE))\nSELECT COUNT(*) ::integer AS count\nFROM\nchild_tables ct\nFULL OUTER JOIN parent_tables pt USING (\"createdId\")\nWHERE\n(pt.\"createdId\" IS NULL\nOR ct.\"createdId\" IS NULL\nOR pt.\"id\" != ct.\"id\"\nOR ct.\"versionId\" != pt.\"versionId\")\nAND ($3::jsonb IS NULL OR LOWER(CASE\nWHEN pt.\"createdId\" IS NULL THEN 'added'\nWHEN ct.\"createdId\" IS NULL THEN 'removed'\nWHEN pt.\"id\" != ct.\"id\" AND ct.\"versionId\" != pt.\"versionId\" THEN 'renamed_and_modified'\nWHEN pt.\"id\" != ct.\"id\" THEN 'renamed'\nWHEN ct.\"versionId\" != pt.\"versionId\" THEN 'modified'\nEND) = ANY(ARRAY(SELECT LOWER(jsonb_array_elements_text($3::jsonb)))))\n") as (fromRevisionId: string, toRevisionId: string, changeTypes: $runtime.InputJsonObject, includeSystem: boolean) => $runtime.TypedSql<countTableDiffsBetweenRevisions.Parameters, countTableDiffsBetweenRevisions.Result>

export namespace countTableDiffsBetweenRevisions {
  export type Parameters = [fromRevisionId: string, toRevisionId: string, changeTypes: $runtime.InputJsonObject, includeSystem: boolean]
  export type Result = {
    count: number | null
  }
}
