
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param fromRevisionId The id of the revision
 * @param toRevisionId The id of the revision
 */
export const hasTableDiffsBetweenRevisions = $runtime.makeTypedQueryFactory("\nSELECT EXISTS (\nWITH\nparent_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $1 AND \"t1\".\"B\" IS NOT NULL))),\nchild_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $2 AND \"t1\".\"B\" IS NOT NULL)))\nSELECT 1\nFROM\nchild_tables ct\nFULL OUTER JOIN parent_tables pt USING (\"createdId\")\nWHERE\npt.\"createdId\" IS NULL OR\nct.\"createdId\" IS NULL OR\nct.\"versionId\" != pt.\"versionId\"\n\nLIMIT 1)") as (fromRevisionId: string, toRevisionId: string) => $runtime.TypedSql<hasTableDiffsBetweenRevisions.Parameters, hasTableDiffsBetweenRevisions.Result>

export namespace hasTableDiffsBetweenRevisions {
  export type Parameters = [fromRevisionId: string, toRevisionId: string]
  export type Result = {
    exists: boolean | null
  }
}
