import {
  addField,
  givenSchemaProjection,
  moveField,
  numberField,
  objectSchema,
  project,
  requiredBlocked,
  requiredProjectionBlocker,
  requiredProjected,
  removeField,
  requiredProjectionRow,
  rowInput,
  stringField,
} from './support/schema-projection-fixture';

describe('Draft Changes schema projection discard', () => {
  it('keeps an independent renamed-field edit under its original coordinate', async () => {
    const headSchema = objectSchema({ price: numberField() });
    const draftSchema = objectSchema({ cost: numberField() });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { price: 10 })],
      draftRows: [rowInput('row-1', { cost: 15 })],
      pending: [
        {
          patches: [moveField('/properties/price', '/properties/cost')],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredProjected(await project(input));

    expect(result.head.schema).toEqual(headSchema);
    expect(result.draft.schema).toEqual(headSchema);
    expect(requiredProjectionRow(result.draft, 'row-1').data).toEqual({
      price: 15,
    });
  });

  it('restores a Head value after discarding a schema removal', async () => {
    const headSchema = objectSchema({
      removed: stringField(),
      kept: stringField(),
    });
    const draftSchema = objectSchema({ kept: stringField() });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { removed: 'head value', kept: 'head' })],
      draftRows: [rowInput('row-1', { kept: 'draft edit' })],
      pending: [
        {
          patches: [removeField('/properties/removed')],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredProjected(await project(input));

    expect(requiredProjectionRow(result.draft, 'row-1').data).toEqual({
      removed: 'head value',
      kept: 'draft edit',
    });
  });

  it('drops an unedited default generated by an added schema field', async () => {
    const headSchema = objectSchema({ name: stringField() });
    const draftSchema = objectSchema({
      name: stringField(),
      category: stringField(''),
    });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { name: 'head' })],
      draftRows: [rowInput('row-1', { name: 'head', category: '' })],
      pending: [
        {
          patches: [addField('/properties/category', stringField(''))],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredProjected(await project(input));

    expect(requiredProjectionRow(result.draft, 'row-1').data).toEqual({
      name: 'head',
    });
  });

  it('blocks when user data depends on a discarded added field', async () => {
    const headSchema = objectSchema({ name: stringField() });
    const draftSchema = objectSchema({
      name: stringField(),
      category: stringField(''),
    });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { name: 'head' })],
      draftRows: [rowInput('row-1', { name: 'head', category: 'custom' })],
      pending: [
        {
          patches: [addField('/properties/category', stringField(''))],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredBlocked(await project(input));

    expect(result.blockers).toContainEqual(
      expect.objectContaining({
        code: 'UNREPRESENTABLE_REMAINDER',
        rowCreatedId: 'row-1',
        path: '/category',
      }),
    );
  });

  it('drops dependent user data only when the caller explicitly identifies it', async () => {
    const headSchema = objectSchema({ name: stringField() });
    const draftSchema = objectSchema({
      name: stringField(),
      category: stringField(''),
    });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { name: 'head' })],
      draftRows: [rowInput('row-1', { name: 'head', category: 'custom' })],
      pending: [
        {
          patches: [addField('/properties/category', stringField(''))],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
      discardedDataFields: [{ rowCreatedId: 'row-1', path: '/category' }],
    });

    const result = requiredProjected(await project(input));

    expect(requiredProjectionRow(result.draft, 'row-1').data).toEqual({
      name: 'head',
    });
  });

  it('blocks a dependent nested field without an explicit data discard', async () => {
    const headSchema = objectSchema({
      details: objectSchema({ name: stringField() }),
    });
    const draftSchema = objectSchema({
      details: objectSchema({ name: stringField(), note: stringField('') }),
    });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { details: { name: 'head' } })],
      draftRows: [
        rowInput('row-1', { details: { name: 'head', note: 'custom' } }),
      ],
      pending: [
        {
          patches: [
            addField('/properties/details/properties/note', stringField('')),
          ],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredBlocked(await project(input));

    expect(requiredProjectionBlocker(result)).toMatchObject({
      code: 'UNREPRESENTABLE_REMAINDER',
    });
  });

  it('preserves an independent sibling while discarding an added field', async () => {
    const headSchema = objectSchema({
      name: stringField(),
      notes: stringField(),
    });
    const draftSchema = objectSchema({
      name: stringField(),
      notes: stringField(),
      category: stringField(''),
    });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { name: 'head', notes: '' })],
      draftRows: [
        rowInput('row-1', { name: 'head', notes: 'independent', category: '' }),
      ],
      pending: [
        {
          patches: [addField('/properties/category', stringField(''))],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredProjected(await project(input));

    expect(requiredProjectionRow(result.draft, 'row-1').data).toEqual({
      name: 'head',
      notes: 'independent',
    });
  });

  it('keeps a Draft-only row while projecting it into the retained schema', async () => {
    const headSchema = objectSchema({ name: stringField() });
    const draftSchema = objectSchema({
      name: stringField(),
      category: stringField(''),
    });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [rowInput('row-1', { name: 'head' })],
      draftRows: [
        rowInput('row-1', { name: 'head', category: '' }),
        rowInput('row-new', { name: 'new', category: '' }),
      ],
      pending: [
        {
          patches: [addField('/properties/category', stringField(''))],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredProjected(await project(input));

    expect(result.draft.rows.map(({ createdId }) => createdId)).toEqual([
      'row-1',
      'row-new',
    ]);
    expect(requiredProjectionRow(result.draft, 'row-new').data).toEqual({
      name: 'new',
    });
  });

  it('preserves a Draft row deletion during schema-only projection', async () => {
    const headSchema = objectSchema({
      name: stringField(),
      category: stringField(''),
    });
    const draftSchema = objectSchema({ name: stringField() });
    const input = givenSchemaProjection({
      operation: 'discard',
      headSchema,
      draftSchema,
      headRows: [
        rowInput('row-1', { name: 'one', category: '' }),
        rowInput('row-2', { name: 'two', category: '' }),
      ],
      draftRows: [rowInput('row-1', { name: 'edited' })],
      pending: [
        {
          patches: [removeField('/properties/category')],
          schema: draftSchema,
        },
      ],
      selectedEffects: [{ historyIndex: 1, patchIndex: 0 }],
    });

    const result = requiredProjected(await project(input));

    expect(result.draft.rows.map(({ createdId }) => createdId)).toEqual([
      'row-1',
    ]);
    expect(requiredProjectionRow(result.draft, 'row-1').data).toEqual({
      name: 'edited',
      category: '',
    });
  });
});
