
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Branches
 * const branches = await prisma.branch.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Branch
 * 
 */
export type Branch = Prisma.BranchModel
/**
 * Model Revision
 * 
 */
export type Revision = Prisma.RevisionModel
/**
 * Model Table
 * 
 */
export type Table = Prisma.TableModel
/**
 * Model Row
 * 
 */
export type Row = Prisma.RowModel
/**
 * Model ProjectVersioningConfig
 * 
 */
export type ProjectVersioningConfig = Prisma.ProjectVersioningConfigModel
/**
 * Model CowRevisionTableState
 * 
 */
export type CowRevisionTableState = Prisma.CowRevisionTableStateModel
/**
 * Model CowDraftState
 * 
 */
export type CowDraftState = Prisma.CowDraftStateModel
/**
 * Model CowTableState
 * 
 */
export type CowTableState = Prisma.CowTableStateModel
/**
 * Model CowTableChunk
 * 
 */
export type CowTableChunk = Prisma.CowTableChunkModel
/**
 * Model CowTableStateChunk
 * 
 */
export type CowTableStateChunk = Prisma.CowTableStateChunkModel
/**
 * Model CowChunkEntry
 * 
 */
export type CowChunkEntry = Prisma.CowChunkEntryModel
/**
 * Model CowRowState
 * 
 */
export type CowRowState = Prisma.CowRowStateModel
/**
 * Model TableMigration
 * 
 */
export type TableMigration = Prisma.TableMigrationModel
