
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const VersioningMode = {
  current: 'current',
  cow: 'cow'
} as const

export type VersioningMode = (typeof VersioningMode)[keyof typeof VersioningMode]


export const CowDraftTableStatus = {
  active: 'active',
  draft_only: 'draft_only',
  deleted: 'deleted'
} as const

export type CowDraftTableStatus = (typeof CowDraftTableStatus)[keyof typeof CowDraftTableStatus]
