
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
export * from "./sql/countRowChangesBetweenRevisions"

export * from "./sql/countTableDiffsBetweenRevisions"

export * from "./sql/getRowChangesPaginatedBetweenRevisions"

export * from "./sql/getRowChangesStatsBetweenRevisions"

export * from "./sql/getTableDiffsPaginatedBetweenRevisions"

export * from "./sql/getTableDiffsStatsBetweenRevisions"

export * from "./sql/hasRowDiffsBetweenRevisions"

export * from "./sql/hasTableDiffsBetweenRevisions"
