
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Branch: 'Branch',
  Revision: 'Revision',
  Table: 'Table',
  Row: 'Row',
  ProjectVersioningConfig: 'ProjectVersioningConfig',
  CowRevisionTableState: 'CowRevisionTableState',
  CowDraftState: 'CowDraftState',
  CowTableState: 'CowTableState',
  CowTableChunk: 'CowTableChunk',
  CowTableStateChunk: 'CowTableStateChunk',
  CowChunkEntry: 'CowChunkEntry',
  CowRowState: 'CowRowState',
  TableMigration: 'TableMigration'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BranchScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  isRoot: 'isRoot',
  name: 'name',
  projectId: 'projectId'
} as const

export type BranchScalarFieldEnum = (typeof BranchScalarFieldEnum)[keyof typeof BranchScalarFieldEnum]


export const RevisionScalarFieldEnum = {
  id: 'id',
  sequence: 'sequence',
  createdAt: 'createdAt',
  comment: 'comment',
  isHead: 'isHead',
  isDraft: 'isDraft',
  isStart: 'isStart',
  hasChanges: 'hasChanges',
  branchId: 'branchId',
  parentId: 'parentId'
} as const

export type RevisionScalarFieldEnum = (typeof RevisionScalarFieldEnum)[keyof typeof RevisionScalarFieldEnum]


export const TableScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  system: 'system'
} as const

export type TableScalarFieldEnum = (typeof TableScalarFieldEnum)[keyof typeof TableScalarFieldEnum]


export const RowScalarFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  publishedAt: 'publishedAt',
  data: 'data',
  meta: 'meta',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type RowScalarFieldEnum = (typeof RowScalarFieldEnum)[keyof typeof RowScalarFieldEnum]


export const ProjectVersioningConfigScalarFieldEnum = {
  projectId: 'projectId',
  versioningMode: 'versioningMode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectVersioningConfigScalarFieldEnum = (typeof ProjectVersioningConfigScalarFieldEnum)[keyof typeof ProjectVersioningConfigScalarFieldEnum]


export const CowRevisionTableStateScalarFieldEnum = {
  revisionId: 'revisionId',
  tableCreatedId: 'tableCreatedId',
  tableStateId: 'tableStateId'
} as const

export type CowRevisionTableStateScalarFieldEnum = (typeof CowRevisionTableStateScalarFieldEnum)[keyof typeof CowRevisionTableStateScalarFieldEnum]


export const CowDraftStateScalarFieldEnum = {
  branchId: 'branchId',
  tableCreatedId: 'tableCreatedId',
  tableStateId: 'tableStateId',
  status: 'status'
} as const

export type CowDraftStateScalarFieldEnum = (typeof CowDraftStateScalarFieldEnum)[keyof typeof CowDraftStateScalarFieldEnum]


export const CowTableStateScalarFieldEnum = {
  id: 'id',
  tableCreatedId: 'tableCreatedId',
  chunkCount: 'chunkCount'
} as const

export type CowTableStateScalarFieldEnum = (typeof CowTableStateScalarFieldEnum)[keyof typeof CowTableStateScalarFieldEnum]


export const CowTableChunkScalarFieldEnum = {
  id: 'id'
} as const

export type CowTableChunkScalarFieldEnum = (typeof CowTableChunkScalarFieldEnum)[keyof typeof CowTableChunkScalarFieldEnum]


export const CowTableStateChunkScalarFieldEnum = {
  tableStateId: 'tableStateId',
  chunkId: 'chunkId',
  chunkNo: 'chunkNo'
} as const

export type CowTableStateChunkScalarFieldEnum = (typeof CowTableStateChunkScalarFieldEnum)[keyof typeof CowTableStateChunkScalarFieldEnum]


export const CowChunkEntryScalarFieldEnum = {
  chunkId: 'chunkId',
  rowCreatedId: 'rowCreatedId',
  rowStateId: 'rowStateId',
  isDeleted: 'isDeleted'
} as const

export type CowChunkEntryScalarFieldEnum = (typeof CowChunkEntryScalarFieldEnum)[keyof typeof CowChunkEntryScalarFieldEnum]


export const CowRowStateScalarFieldEnum = {
  id: 'id',
  rowCreatedId: 'rowCreatedId',
  rowId: 'rowId',
  readonly: 'readonly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  publishedAt: 'publishedAt',
  data: 'data',
  meta: 'meta',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type CowRowStateScalarFieldEnum = (typeof CowRowStateScalarFieldEnum)[keyof typeof CowRowStateScalarFieldEnum]


export const TableMigrationScalarFieldEnum = {
  id: 'id',
  revisionId: 'revisionId',
  tableId: 'tableId',
  sourceTableVersionId: 'sourceTableVersionId',
  shadowTableVersionId: 'shadowTableVersionId',
  status: 'status',
  phase: 'phase',
  patches: 'patches',
  previousSchema: 'previousSchema',
  previousSchemaHash: 'previousSchemaHash',
  targetSchemaHash: 'targetSchemaHash',
  totalRows: 'totalRows',
  copiedRows: 'copiedRows',
  lastCopiedRowId: 'lastCopiedRowId',
  batchSize: 'batchSize',
  currentBatch: 'currentBatch',
  totalBatches: 'totalBatches',
  createdAt: 'createdAt',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  lastProgressAt: 'lastProgressAt',
  lockedBy: 'lockedBy',
  lockedAt: 'lockedAt',
  heartbeatAt: 'heartbeatAt',
  errorMessage: 'errorMessage',
  retryCount: 'retryCount',
  maxRetries: 'maxRetries'
} as const

export type TableMigrationScalarFieldEnum = (typeof TableMigrationScalarFieldEnum)[keyof typeof TableMigrationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const BranchOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  projectId: 'projectId'
} as const

export type BranchOrderByRelevanceFieldEnum = (typeof BranchOrderByRelevanceFieldEnum)[keyof typeof BranchOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const RevisionOrderByRelevanceFieldEnum = {
  id: 'id',
  comment: 'comment',
  branchId: 'branchId',
  parentId: 'parentId'
} as const

export type RevisionOrderByRelevanceFieldEnum = (typeof RevisionOrderByRelevanceFieldEnum)[keyof typeof RevisionOrderByRelevanceFieldEnum]


export const TableOrderByRelevanceFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id'
} as const

export type TableOrderByRelevanceFieldEnum = (typeof TableOrderByRelevanceFieldEnum)[keyof typeof TableOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const RowOrderByRelevanceFieldEnum = {
  versionId: 'versionId',
  createdId: 'createdId',
  id: 'id',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type RowOrderByRelevanceFieldEnum = (typeof RowOrderByRelevanceFieldEnum)[keyof typeof RowOrderByRelevanceFieldEnum]


export const ProjectVersioningConfigOrderByRelevanceFieldEnum = {
  projectId: 'projectId'
} as const

export type ProjectVersioningConfigOrderByRelevanceFieldEnum = (typeof ProjectVersioningConfigOrderByRelevanceFieldEnum)[keyof typeof ProjectVersioningConfigOrderByRelevanceFieldEnum]


export const CowRevisionTableStateOrderByRelevanceFieldEnum = {
  revisionId: 'revisionId',
  tableCreatedId: 'tableCreatedId',
  tableStateId: 'tableStateId'
} as const

export type CowRevisionTableStateOrderByRelevanceFieldEnum = (typeof CowRevisionTableStateOrderByRelevanceFieldEnum)[keyof typeof CowRevisionTableStateOrderByRelevanceFieldEnum]


export const CowDraftStateOrderByRelevanceFieldEnum = {
  branchId: 'branchId',
  tableCreatedId: 'tableCreatedId',
  tableStateId: 'tableStateId'
} as const

export type CowDraftStateOrderByRelevanceFieldEnum = (typeof CowDraftStateOrderByRelevanceFieldEnum)[keyof typeof CowDraftStateOrderByRelevanceFieldEnum]


export const CowTableStateOrderByRelevanceFieldEnum = {
  id: 'id',
  tableCreatedId: 'tableCreatedId'
} as const

export type CowTableStateOrderByRelevanceFieldEnum = (typeof CowTableStateOrderByRelevanceFieldEnum)[keyof typeof CowTableStateOrderByRelevanceFieldEnum]


export const CowTableChunkOrderByRelevanceFieldEnum = {
  id: 'id'
} as const

export type CowTableChunkOrderByRelevanceFieldEnum = (typeof CowTableChunkOrderByRelevanceFieldEnum)[keyof typeof CowTableChunkOrderByRelevanceFieldEnum]


export const CowTableStateChunkOrderByRelevanceFieldEnum = {
  tableStateId: 'tableStateId',
  chunkId: 'chunkId'
} as const

export type CowTableStateChunkOrderByRelevanceFieldEnum = (typeof CowTableStateChunkOrderByRelevanceFieldEnum)[keyof typeof CowTableStateChunkOrderByRelevanceFieldEnum]


export const CowChunkEntryOrderByRelevanceFieldEnum = {
  chunkId: 'chunkId',
  rowCreatedId: 'rowCreatedId',
  rowStateId: 'rowStateId'
} as const

export type CowChunkEntryOrderByRelevanceFieldEnum = (typeof CowChunkEntryOrderByRelevanceFieldEnum)[keyof typeof CowChunkEntryOrderByRelevanceFieldEnum]


export const CowRowStateOrderByRelevanceFieldEnum = {
  id: 'id',
  rowCreatedId: 'rowCreatedId',
  rowId: 'rowId',
  hash: 'hash',
  schemaHash: 'schemaHash'
} as const

export type CowRowStateOrderByRelevanceFieldEnum = (typeof CowRowStateOrderByRelevanceFieldEnum)[keyof typeof CowRowStateOrderByRelevanceFieldEnum]


export const TableMigrationOrderByRelevanceFieldEnum = {
  id: 'id',
  revisionId: 'revisionId',
  tableId: 'tableId',
  sourceTableVersionId: 'sourceTableVersionId',
  shadowTableVersionId: 'shadowTableVersionId',
  status: 'status',
  phase: 'phase',
  previousSchemaHash: 'previousSchemaHash',
  targetSchemaHash: 'targetSchemaHash',
  lastCopiedRowId: 'lastCopiedRowId',
  lockedBy: 'lockedBy',
  errorMessage: 'errorMessage'
} as const

export type TableMigrationOrderByRelevanceFieldEnum = (typeof TableMigrationOrderByRelevanceFieldEnum)[keyof typeof TableMigrationOrderByRelevanceFieldEnum]

