name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: cp .env.example .env

      - run: npm ci --ignore-scripts

      - run: npm run lint:ci

      - run: npm run tsc

      - run: npm run docker:test-container-up

      - name: Setup test database
        run: |
          cp .env.test .env
          npx prisma db push --force-reset --accept-data-loss
        env:
          DATABASE_URL: postgresql://engine:password@localhost:5440/engine-test

      - name: Restore jest cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .jest-cache
          key: jest-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            jest-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            jest-cache-${{ runner.os }}-

      - run: npm run test:ci
        env:
          DATABASE_URL: postgresql://engine:password@localhost:5440/engine-test

      - run: npm run docker:test-container-down

      - uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
